### ISSUE TITLE
Use path relative to my app rather than full path.

### ISSUE THREAD

**Issue by xpol** [luvit/luvi#136]
When my luvit app crashes, it reports full path of lua files.
When the path is too long to display, it was truncated with ...

This is not friendly for look up errors and not for possible for editors capture errors.
Is it possible to force luvit use path relative to my app root rather than full path.

**Comment by creationix** [comment]
I'm not sure how this could be done.  Luvi has no concept of luvit app roots.

**Comment by xpol** [comment]
Where does luvi resolve path to full path or actually it all done by luajit? I'd like to check if it is possible to add something like app root. Something like rake do:

>$ rake
>  (in /Users/abc/src)
>  ...

**Comment by truemedian** [comment]
The "module name" for things like Lua errors is determined by the name passed to `load`/`loadstring`. In a normal Luvit project this is handled by the `luvit/require` package. If this behavior is really warranted an issue should be opened in the Luvit repository, not here as Luvi has no say in how that is implemented.
