### ISSUE TITLE
Build breaks on Mac OSX 10.11

### ISSUE THREAD

**Issue by xpol** [luvit/luvi#142]
the commit a3ec57f fail to build, but 2.6.1 build well.

make regular
make test

got:

[ 99%] Linking C executable luvi
Undefined symbols for architecture x86_64:
  "_CRYPTO_thread_setup", referenced from:
      _luaopen_openssl in liblua_openssl.a(openssl.c.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[3]: *** [luvi] Error 1
make[2]: *** [CMakeFiles/luvi.dir/all] Error 2
make[1]: *** [all] Error 2
make: *** [luvi] Error 2

**Comment by creationix** [comment]
Yep, I can confirm this regression. @starwing, can you look into this?

**Comment by starwing** [comment]
@creationix Okay, I will look into this, sorry for that :(

**Comment by starwing** [comment]
it seems in Mac OS X the `PTHREADS` symbol not defined [1], I don't have a Mac machine, so maybe you can try out this method:

[1]: https://github.com/luvit/luvi/blob/a3ec57fe2e895a562645b9eac4aed79a06f9d49b/deps/lua-openssl.cmake#L8

1. update submodule `lua-openssl` to latest (auther modified a bug that cause I write [1]).
2. modify this in [1]:
```
find_package(Threads)
if (CMAKE_THREAD_LIBS_INIT)
    add_definitions(-DPTHREADS)
endif (CMAKE_THREAD_LIBS_INIT)
```
 to:
```
add_definitions(-DPTHREADS)
```

always define PTHREADS symbol.

after that you can try out it.

p.s. Do you have `pthread` in your mac? can you paste out your cmake congfuration log. if you don't have pthread library, the error is expectable.

**Comment by creationix** [comment]
Ok, got OSX working, now to see if windows, linux, and bsd still work.
