### ISSUE TITLE
Download package of source files for v2.6.x

### ISSUE THREAD

**Issue by joerg-krause** [luvit/luvi#144]
Starting with v2.6.0 no more download packages of the source files, e.g. luvi-src-v2.5.2.tar.gz, are provided. I'd like to update the luvi version for the [Buildroot package](https://git.busybox.net/buildroot/tree/package/luvi/luvi.mk), which uses the distributed source files.

**Comment by creationix** [comment]
Sorry, I forgot to publish the tarballs.  I just published the tarballs for v2.6.0 and v2.6.1.
