### ISSUE TITLE
Build system should change

### ISSUE THREAD

**Issue by milani** [luvit/luvi#153]
According to different discussions like #109, I suppose supporting embedded devices is a target for luv and luvi. But the build system does not allow this.

During the build, luajit needs some binaries to be built on the HOST system (buildvm and minilua) and CMAKE does not allow two compilers to run, you should either build for cross-compiling or not. 

Another issue is that luvi uses luajit at some stage in the build process to generate byte-codes for some lua scripts, if we cross-compile, luajit won't run on the host machine.

I think moving to another build system like gyp or pure Makefile would solve the first issue. For the second, we can force two builds of luajit, one for host, one for target.

**Comment by joerg-krause** [comment]
You can cross build luv and luvi with (Buildroot)[https://buildroot.org/].

**Comment by milani** [comment]
Problem is not using a toolchain. It is that luajit and luvi need to build some parts for host not the target and cmake can not do this.

**Comment by joerg-krause** [comment]
Buildroot is not only a toolchain, but a build system to ease building a package. What it does in case of luvi is to build a host variant of LuaJIT to cross build a luvi target: https://github.com/buildroot/buildroot/blob/master/package/luvi/luvi.mk.

And it uses CMake to build this package.

**Comment by milani** [comment]
I could get it to work on OpenWRT by two rounds of luajit builds, one for host and one for target. Also we can avoid this by changing the build script to make things easy, it works for now.
