### ISSUE TITLE
How to override print function

### ISSUE THREAD

**Issue by LoganDark** [luvit/luvi#154]
I've been trying to override the print function. I've tried `_G.print` and `print`. Is there any way to do this?

**Comment by creationix** [comment]
yes, you can set _G.print to override it. I do this in the luvit pretty-print package. https://github.com/luvit/luvit/blob/master/deps/pretty-print.lua#L295-L304

**Comment by LoganDark2** [comment]
it seems that `pcall(func)` does not use _G. is that true?

**Comment by LoganDark2** [comment]
if it is, how to I `pcall

**Comment by LoganDark2** [comment]
@creationix

**Comment by creationix** [comment]
`pcall` should work.  See also http://www.freelists.org/post/luajit/pcallxpcall-broken-in-v21-if-JITed

**Comment by creationix** [comment]
FWIW, I released a new luvi, lit, luvit, and friends yesterday that has the fix from luajit mentioned in that post.  Try again after updating just in case that was the problem.

**Comment by LoganDark2** [comment]
The issue is a function called with pcall can't access the functions I define before running it

**Comment by creationix** [comment]
How are you defining them?

**Comment by LoganDark2** [comment]
Thru _g and normally

**Comment by creationix** [comment]
How exactly?  There is no such global `_g`, the case matters.

In other words, share a snippet of code that reproduces the problem.  Luvit obviously customizes print globally and it works great.  So we know it's possible, but something is wrong with your code.

**Comment by LoganDark2** [comment]
I meant _G

**Comment by squeek502** [comment]
Perhaps unlikely, but make sure the function's environment is not being changed (by `setfenv`) before it gets `pcall`'d. For example, this would cause the problem you're talking about:

```lua
local oldprint = _G["print"]
_G["print"] = function(...) oldprint("New print called") end

local callee = function()
    print("This shouldn't print")
end

setfenv(callee, {print = oldprint})
pcall(callee)
```

running that would output:
```
> lua test.lua
This shouldn't print
```
