### ISSUE TITLE
luvi fails to build from source trying to statically link openSSL.

### ISSUE THREAD

**Issue by caryhaynie** [luvit/luvi#162]
See attached error.log.

[error.log](https://github.com/luvit/luvi/files/1389397/error.log)

Also occurs on Windows, can attach error log from there if needed.

**Comment by zhaozg** [comment]
ok assign to @zhaozg

**Comment by caryhaynie** [comment]
[win_error.log](https://github.com/luvit/luvi/files/1395015/win_error.log)

It looks like some of the 5.3 compatibility stuff is busted.

**Comment by zhaozg** [comment]
Can you try update dep/lua-openssl to latest version?

**Comment by caryhaynie** [comment]
updating lua-openssl to master (via 'git pull --recurse-submodules=on-demand origin master' in deps/lua-openssl) fixes both the windows and osx builds. Thanks for the prompt work!
