### ISSUE TITLE
aarch64 failure to install precompiled binaries

### ISSUE THREAD

**Issue by TheWaffleDimension** [luvit/luvi#166]
Currently getting a "No such file or directory" for both the tiny and normal aarch64 binaries. I'm attempting to install on Termux.

**Comment by creationix** [comment]
I think it's because there is a libc mismatch.  I've seen similar errors mixing glibc and musl-libc.  Try running `file` in the binary and see if the libc mentioned exists on your system.

**Comment by TheWaffleDimension** [comment]
```
./luvi-regular-Linux_aarch64: ELF 64-bit LSB executable, ARM aarch64, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux-aarch64.so.1, for GNU/Linux 3.7.0, BuildID[sha1]=3b47e0a5a012ae292ec6de0dba118e091c13b4ef, not stripped
```
This is the result of file. Based on this, perhaps `ld-linux` is missing. It's probably due to Termux being a terminal emulator, and not an actual linux install.

**Comment by creationix** [comment]
I'm pretty sure android doesn't use normal libc, termux is a real-enough userspace linux, but it doesn't require rooted phones and so can't do all things.

**Comment by zhaozg** [comment]
LuaJIT V2.1 is better for Linux-aarch64

**Comment by SinisterRectus** [comment]
I don't know where it's defined (LuaJIT is not a dep for luvi?), but I think we already use LuaJIT 2.1, according to `jit.version`.
