### ISSUE TITLE
LPEG's re.lua module not included with luvi?

### ISSUE THREAD

**Issue by Mehgugs** [luvit/luvi#167]
re.lua is a simple pure-lua module that provides string pattern syntax for lpeg (like regex/lua patterns). Although you can easily inlcude the file in your projects it should be part of the deps as it is part of the standard lpeg distribution.

I notice it's included in the lpeg repo in `/deps` so perhaps I am missing something but it is definitely not available using `require("re")` nor is it included in the lpeg module itself.

http://www.inf.puc-rio.br/~roberto/lpeg/re.html

**Comment by zhaozg** [comment]
p(require're')
