### ISSUE TITLE
warning: implicit declaration of function ‘luvi_openlibs'

### ISSUE THREAD

**Issue by Timothy-** [luvit/luvi#173]
Since 3a444d1 luvi_openlibs is undeclared.

https://travis-ci.org/luvit/luvi/jobs/388593852#L851

> /home/travis/build/luvit/luvi/src/main.c: In function ���vm_acquire’:
/home/travis/build/luvit/luvi/src/main.c:63:3: warning: implicit declaration of function ‘luvi_openlibs’ [-Wimplicit-function-declaration]
   luvi_openlibs(L);
   ^

Also, could you add -Wno-unused-function to CMakeLists.txt to disable all the luv warnings?

**Comment by zhaozg** [comment]
Ok, assign to me.

好的，我来处理

**Comment by zhaozg** [comment]
fixed in https://github.com/luvit/luvi/commit/8fd9c8b637b3a312c14dec7af5eae0e941f4fe5d
