### ISSUE TITLE
Update openssl included or switch to shared ssl from system.

### ISSUE THREAD

**Issue by creationix** [luvit/luvi#178]
I vote we switch to using the system shared openssl by default so that we get OS updates for free.  We don't have the resources to keep our version up to date anymore.  We haven't updated since 2016 I believe.

@zhaozg @rphillips what do you think?

**Comment by rphillips** [comment]
Changing to default makes sense. The windows build might break since it won't have those libraries installed by default (for unit tests). Hopefully we could preserve the windows ssl testing.

/cc @itzg

**Comment by creationix** [comment]
Yeah, OSX doesn't tend to have system openssl either.  Maybe do shared just on linux.

Also @zhaozg what version of `lua-openssl` will work with modern openssl versions?  I get compile errors when switching the build flag to shared.  My machine has `OpenSSL 1.1.0h  27 Mar 2018`

**Comment by creationix** [comment]
Nevermind, the current version of `lua-openssl` works.  It was the intermetitet build failure around `hash.h` in luajit.

I've got a shiny updated openssl on my archlinix version!

```
./build/luvi v2.8.0-39-ge30a72e
rex: 8.37 2015-04-28
libuv: 1.22.0
ssl: OpenSSL 1.1.0h  27 Mar 2018, lua-openssl 0.7.1
```

**Comment by zhaozg** [comment]
pr will ready next day

**Comment by zhaozg** [comment]
If we want to follow latest openssl, Can me consider using  [cmake ExternalProject](https://cmake.org/cmake/help/v3.0/module/ExternalProject.html?highlight=externalproject_add)  to use openssl office build system?

**Comment by rphillips** [comment]
ExternalProject looks reasonable.

**Comment by squeek502** [comment]
The shared openssl by default on Linux has given a few people some problems. Just wanted to log some recent issues brought up in the Discord here in case shared openssl by default is something we want to revisit:

> Lautenschlager | Today at 3:42 PM
> I am having a glibc problem when I try to host my bot on heroku.

> I checked Luvi's repo and the last update was 6 days ago, so that shouldn't be the problem...

> There's no way to reproduce it through code. It happens when I try to push my project. I understand it's something about the openssl module...

> ![](https://cdn.discordapp.com/attachments/377966879639207936/552999385785434134/unknown.png)

> ![](https://media.discordapp.net/attachments/377966879639207936/552999705857097747/unknown.png)

---

> Nameless | Last Sunday at 6:39 PM
> i was getting an openssl fatal out of secure-socket NYI, openssl below 1.0.2 not fully support this feature
> i might need to compile luvi myself
> which would be annoying
> [lots of debugging to get them set up with a working self-compiled luvi, lit, luvit]

**Comment by creationix** [comment]
Maybe we can keep openssl static in the builds we publish, but default to shared when people build their own?

Also I saw that same error when I build on ubuntu 14.04 and then tried to run on ubuntu 18.04.  I wonder if building on a newer host would help?

**Comment by joerg-krause** [comment]
The binary should be build on the oldest system you want to support. This is because of the compatibility of the glibc library, which is backward compatible. As luvi does not support all version of, e.g. OpenSSL 1.0.2, 1.1.0, and 1.1.1 the binary you want to distribute should be build statically against OpenSSL.

**Comment by squeek502** [comment]
Maybe just make building with shared openssl a bit more convenient by adding a `regular-shared` make target?
