### ISSUE TITLE
Rebuild Binaries with CrossPlatform enabled binaries.

### ISSUE THREAD

**Issue by rphillips** [luvit/luvi#195]
Using HolyBuild or some other flavor of cross platform binary builds.

ref: https://github.com/luvit/luvi/pull/192

**Comment by rphillips** [comment]
I uploaded new binaries using `sudo make linux-build` which uses the holy-build environment.

**Comment by squeek502** [comment]
Why are the Linux binaries so big now? 9.46 MB compared to 4.16 MB of Luvi 2.7.6?

**Comment by SinisterRectus** [comment]
The only thing I know of is our miniz expansion a while back, but it was reported to only contribute 8 kb. #165

**Comment by joerg-krause** [comment]
The luvi 2.9.1 release is build with debug infos, whereas luvi 2.7.6 is build without.
