### ISSUE TITLE
bitops don't work with int64 type

### ISSUE THREAD

**Issue by creationix** [luvit/luvi#207]
I just noticed a regression in my cbor code from moving back to the older version of luajit.

In luajit 2.1.x you can perform bit operations on 64 bit integer cdata values, but our current version of lua fails.

```lua
$ luajit
LuaJIT 2.1.0-beta3 -- Copyright (C) 2005-2017 Mike Pall. http://luajit.org/
JIT: ON SSE2 SSE3 SSE4.1 BMI2 fold cse dce fwd dse narrow loop abc sink fuse
> =bit.lshift(1ULL,2)
4ULL
```

``` 
$ luvit
Welcome to the Luvit repl!
> bit.lshift(1ULL,2)
bad argument #1 to '?' (number expected, got cdata)
stack traceback:
	[builtin#69]: at 0x00497db0
	[C]: in function 'xpcall'
	[string "bundle:deps/repl.lua"]:97: in function 'evaluateLine'
	[string "bundle:deps/repl.lua"]:189: in function <[string "bundle:deps/repl.lua"]:187>
```

**Comment by creationix** [comment]
Yet another reason to upgrade again to newer luajit.

**Comment by creationix** [comment]
I started a PR for luv to see if this fixes this https://github.com/luvit/luv/pull/365

**Comment by creationix** [comment]
Not having bitops on 64bit integers actually breaks a lot of my modules.  My pure lua blake2b and sha256/sha512 modules are also now broken using default luvi builds.  Hence the PR above.

**Comment by creationix** [comment]
https://github.com/luvit/luvi/pull/212

**Comment by SinisterRectus** [comment]
I believe this was fixed with the LuaJIT update.

```
C:\Users\Sinister\Desktop>luvit -v
luvit version: 2.17.0
luvi version: v2.11.0
libuv version: 1.34.2
rex version: 8.37 2015-04-28
winsvc version: 1.0.0
ssl version: OpenSSL 1.1.1d  10 Sep 2019, lua-openssl 0.7.7

C:\Users\Sinister\Desktop>luvit
Welcome to the Luvit repl!
> bit.lshift(1ULL, 2)
4ULL
```
