### ISSUE TITLE
Support for LuaJIT GC64

### ISSUE THREAD

**Issue by SinisterRectus** [luvit/luvi#211]
OpenResty now uses GC64 mode by default. This allows for more than 2 GB memory on 64-bit systems. Is there any interest in doing the same for luvi(t)?

See: https://blog.openresty.com/en/luajit-gc64-mode/

**Comment by aiverson** [comment]
Yes, that's bitten me before. I am strongly in favor of enabling GC64 mode by default. I think I tried making a custom build with that a couple years ago but I don't remember whether it worked or not.

**Comment by creationix** [comment]
Sounds good to me.  I assume this requires a PR to luv to change the build config for luajit right?

**Comment by SinisterRectus** [comment]
I honestly have no idea. I didn't realize LuaJIT was configured at the luv level. It looks like this is the relevant openresty commit: https://github.com/openresty/openresty/commit/3f42731e5

**Comment by creationix** [comment]
I did a quick test and tried enabling the feature on linux x64 and it broke lots of stuff.  This will require some time to make sure we do it right.

**Comment by SinisterRectus** [comment]
That's a shame. Coincidentally, I was just working on it, too. Although, I'm only just trying to figure out how to properly configure the mode. Using only the `LuaJIT-2.1.0-beta3` source, enabling the `DLUAJIT_ENABLE_GC64` flag doesn't seem to have an effect on the memory limit, so I'm not sure if I'm even doing it right.

```
# Enable GC64 mode for x64.
XCFLAGS+= -DLUAJIT_ENABLE_GC64
```
```
make
./src/luajit main.lua
```
```lua
collectgarbage()

assert(jit.arch == 'x64')

local t = {}
local n  = 1000000

for i = 1, n do
    t[i] = {}
    for j = 1, n do
        t[i][j] = {}
    end
    print(collectgarbage('count'))
end
```
![image](https://user-images.githubusercontent.com/11720541/62314690-98ce6000-b461-11e9-9c9b-d8352ca3d057.png)

**Comment by SinisterRectus** [comment]
I just realized that my VPS only has 1 GB of memory, so of course the process wouldn't be able to surpass that. Whoops.

**Comment by MikuAuahDark** [comment]
Mike Pall pushed lots of commits in December and one of it is LuaJIT/LuaJIT@bd00094c3b50e193fb32aad79b7ea8ea6b78ed25

So maybe try again building with GC64?

**Comment by SinisterRectus** [comment]
With luvit/luv#449 and [release1.34.1](https://github.com/luvit/luv/releases/tag/1.34.1-0), luv now includes this GC64 configuration for LuaJIT.

**Comment by zhaozg** [comment]
closed by https://github.com/luvit/luvi/commit/60b226e5c4ed7da7e121dc11e079d568602c458a, luajit v2.1 make GC64 enabled.
