### ISSUE TITLE
v2.9.1 luvi-regular-Linux_x86_64 binary no longer exports lua symbols

### ISSUE THREAD

**Issue by DirtYiCE** [luvit/luvi#219]
Between v2.9.0 and 2.9.1 the size of the regular linux x86_64 binary increased from 1.53MB to 9.46MB (this looks like because it statically links openssl now instead of depending on an ancient .so being available on the system) while it no longer exports `lua_*` symbols, breaking binary modules (but it apparently exports the whole openssl and libuv). I couldn't find anything related to this in the changelog or the 2 commits between the 2 releases, I think the new release is compiled somehow differently than the previous one. Is it possible to fix this?

**Comment by SinisterRectus** [comment]
Is this an issue in 2.9.2 or 2.9.3?

**Comment by SinisterRectus** [comment]
It looks like the `regular-shared` target is a fix for this, added in #205.

**Comment by DirtYiCE** [comment]
There's no 2.9.2 binary release, but 2.9.3 has the same issue.

**Comment by squeek502** [comment]
The release binaries are now built via CI:

https://github.com/luvit/luvi/blob/2ced4295fda08ab3448fa955d11220cc244fc6c2/.travis.yml#L40-L61

which uses `make linux-build`:

https://github.com/luvit/luvi/blob/2ced4295fda08ab3448fa955d11220cc244fc6c2/Makefile#L124-L132

which uses `packaging/holy-build.sh` for wider Linux compatibility:

https://github.com/luvit/luvi/blob/2ced4295fda08ab3448fa955d11220cc244fc6c2/packaging/holy-build.sh#L1-L26

It might be the `strip --strip-all` added in https://github.com/luvit/luvi/commit/d104cb7ef9b445175a30fb3df878a7c47d15c458? But, if so, that would only affect 2.9.3, not 2.9.1 (although 2.9.1 was before CI, so the binaries could have been stripped manually).

**Comment by squeek502** [comment]
I think this will be fixed by https://github.com/luvit/luvi/pull/221 but I'm not positive I'm checking for the right thing.

You said that both 2.9.1 and 2.9.3 were affected, could you let me know how you are testing/checking that?

For me, with 2.9.1:
```
$ wget https://github.com/luvit/luvi/releases/download/v2.9.1/luvi-regular-Linux_x86_64 && mv luvi-regular-Linux_x86_64 luvi-2.9.1
$ nm luvi-2.9.1 | grep lua_
00000000004810d0 t lua_atpanic
00000000004cb070 t lua_call
00000000004c2550 t lua_checkstack
00000000004c1830 t lua_close
...
```
with 2.9.3:
```
$ wget https://github.com/luvit/luvi/releases/download/v2.9.3/luvi-regular-Linux_x86_64 && mv luvi-regular-Linux_x86_64 luvi-2.9.3
$ nm luvi-2.9.3
nm: luvi-2.9.3: no symbols
```

**Comment by squeek502** [comment]
Maybe due to [`-fvisibility=hidden` in the holy-build-box `CFLAGS`](https://github.com/phusion/holy-build-box/blob/a8398138bd5af1b5545c2a621e19dae8413174ef/image/activate_func.sh#L35)?

**Comment by DirtYiCE** [comment]
@squeek502 
I think you should use `nm -D` instead of simply `nm` to display the dynamic symbols used by the dynamic linker. In that case I see:
```
$ nm -D luvi-2.9.0 | grep lua_ | head -n3
00000000004578c0 T lua_atpanic
00000000004a6080 T lua_call
000000000049cab0 T lua_checkstack
$ nm -D luvi-2.9.1 | grep lua_
$ nm -D luvi-2.9.3 | grep lua_
```

**Comment by squeek502** [comment]
@DirtYiCE Okay, thanks. #222 should fix this, then. On that branch:

```
$ make linux-build-box-regular
$ nm -D luvi-regular-Linux_x86_64 | grep lua_ | head -n3
000000000049aec0 T lua_atpanic
00000000004ee150 T lua_call
00000000004e4f70 T lua_checkstack
```

**Comment by DirtYiCE** [comment]
@squeek502 Cool. Is there any way to download the binary from travis?

**Comment by squeek502** [comment]
Not that I'm aware of. I'll make sure to release a new version once #222 is reviewed/merged.

**Comment by squeek502** [comment]
Here's a locally built version if you want to try that out:

[luvi-regular-Linux_x86_64.zip](https://github.com/luvit/luvi/files/3963417/luvi-regular-Linux_x86_64.zip)

**Comment by DirtYiCE** [comment]
Thanks, lua modules work with that version, but now pcre gives me headache (apparently my binary module needs pcre too and luvit exports one too...). I think I'll just try to compile it on my own after all.
