### ISSUE TITLE
Termux/aarch64: Segfaults at 97% build progress

### ISSUE THREAD

**Issue by athraxkobal** [luvit/luvi#230]
Cloning and doing "make regular" works as intended, but building luvi tends to display segfaults at 97% or 98%
The build process runs fine until 97%, where "jitted_tmp/src/lua/init.lua_luvi_generated.o" and
"jitted_tmp/src/lua/luvibundle.lua_luvi_generated.o" both segfault.
At 98%, "jitted_tmp/src/lua/init.lua_luvi_generated.o" segfaults again and "jitted_tmp/deps/lpeg/re.lua_luvi_generated.o" joins the party.

Screenshot: https://cdn.discordapp.com/attachments/598878518570385420/687727043022290992/Screenshot_20200312-1419541.png

This error occasionally pops up around here: 
deps/luv/luajit: ./jit/bcsave.lua:0: attempt to compare two table values

**Comment by joev** [comment]
Having the same issue. Anyone looked into this yet? Really want to be able to run luvit on my Raspberry PIs :D

**Comment by Pechu317** [comment]
fix found! thanks to Nameless (aka truemedian) for this.
just run these two lines and wait for it to compile:
`export PREFIX=.`
`curl -L https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh`

**Comment by Bilal2453** [comment]
Just to clear stuff out. The build did indeed work on a aarch64 using that script, not necessary fixed, might just mean your exact setup had a less chance of encountering the same segfault. Will have to do more investigating on this.

**Comment by squeek502** [comment]
`luvit-bin` uses `make regular-asm` while the OP is using `make regular`. Can anyone confirm if `make regular-asm` avoids the segfault?

**Comment by athraxkobal** [comment]
> `luvit-bin` uses `make regular-asm` while the OP is using `make regular`. Can anyone confirm if `make regular-asm` avoids the segfault?

Tried just now, no.
![Screenshot_20210320-200951~2](https://user-images.githubusercontent.com/16199845/111889078-91522680-89b8-11eb-8202-c64c9424bfb0.png)

**Comment by truemedian** [comment]
This is making a lot less sense than it should, could it possibly be a Termux bug?

**Comment by Bilal2453** [comment]
> This is making a lot less sense than it should, could it possibly be a Termux bug?

that is a high chance indeed, but according to @drveoj, this did happen with their Raspberry as well as Termux.

> Tried just now, no.

@athraxkobal Can you try the instructions in this reply? if you haven't already

> `export PREFIX=.`
> `curl -L https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh`

**Comment by athraxkobal** [comment]
@Bilal2453 Fails the exact same way after looking at the install.log

**Comment by drveoj** [comment]
> 
> 
> @Bilal2453 Fails the exact same way after looking at the install.log

Happy to pitch in on the Raspberry side if I can help...

**Comment by truemedian** [comment]
I've debugged this farther than I wanted to, it appears to be a bug in aarch64 luajit. If anyone has an actual aarch64 machine and the knowledge, we might want to submit a bug report to luajit about this.

**Comment by drveoj** [comment]
Just to confirm (for the absence of doubt) this doesn't work on PI(4) 

```
Linux ember 5.4.0-1030-raspi #33-Ubuntu SMP PREEMPT Wed Feb 24 11:20:11 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
```
_curl -L https://github.com/truemedian/luvit-bin/raw/main/install.sh | sh_ yeilds: 
```
[ 97%] Building Luajitted /home/joev/bot/luvi.d/src/lua/luvibundle.lua: /home/joev/bot/luvi.d/build/jitted_tmp/src/lua/luvibundle.lua_luvi_generated.o
make[2]: *** [CMakeFiles/luvi.dir/build.make:73: jitted_tmp/src/lua/luvibundle.lua_luvi_generated.o] Segmentation fault (core dumped)
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [CMakeFiles/luvi.dir/build.make:63: jitted_tmp/src/lua/init.lua_luvi_generated.o] Segmentation fault (core dumped)
make[2]: *** [CMakeFiles/luvi.dir/build.make:78: jitted_tmp/deps/lpeg/re.lua_luvi_generated.o] Segmentation fault (core dumped)
make[2]: *** [CMakeFiles/luvi.dir/build.make:68: jitted_tmp/src/lua/luvipath.lua_luvi_generated.o] Segmentation fault (core dumped)
make[1]: *** [CMakeFiles/Makefile2:190: CMakeFiles/luvi.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by wozeparrot** [comment]
I bisected luajit to this bad commit: [3143b218946395834f0bfef741061ac6ef3f5b56](https://github.com/LuaJIT/LuaJIT/commit/3143b218946395834f0bfef741061ac6ef3f5b56).

Not really sure how to proceed from here.

**Comment by Bilal2453** [comment]
Can indeed confirm it compiles just fine on aarch64 on the commit before 3143b218, [78f5f1cef](https://github.com/LuaJIT/LuaJIT/commit/78f5f1cef19502289604299e4e6d00e14411f764). Thanks @wozeparrot, now good luck knowing how that commit broke things, it is quite a large one.

**Comment by squeek502** [comment]
> By patching the luajit.cmake file in luv to add `-DENDIAN_LE` to `DASM_FLAGS` will allow luvi to build with no issues on aarch64.

Could [`CMAKE_C_BYTE_ORDER`](https://cmake.org/cmake/help/latest/variable/CMAKE_LANG_BYTE_ORDER.html#variable:CMAKE_%3CLANG%3E_BYTE_ORDER) be used to determine when to pass this flag?

**Comment by truemedian** [comment]
A quick glance at Luajit's makefile shows that luvit's cmake file for building luajit is out of sync.

[luvit](https://github.com/luvit/luv/blob/master/deps/luajit.cmake#L155-L158) vs [luajit](https://github.com/LuaJIT/LuaJIT/blob/v2.1/src/Makefile#L403-L407). I'll take a look at this in more detail so that this same issue doesn't pop back up on us and submit a PR to luv.

**Comment by truemedian** [comment]
If endianness does actually happen to be the only issue here, then luvit/luv#570 *should* fix this issue once and for all.

However, in the interest of keeping the rest of the cmake file still functional on older versions of luajit I only added the few missing things. In the future it probably needs to be reworked or redone to be more in line with the current luajit makefile.
