### ISSUE TITLE
Update to OpenSSL 1.1.1g

### ISSUE THREAD

**Issue by squeek502** [luvit/luvi#232]
https://www.openssl.org/news/secadv/20200421.txt

Might be as simple as updating the CMake file:

https://github.com/luvit/luvi/blob/9da12caaf01337ef0609d07b2af9a5296c13922a/deps/openssl.cmake#L31-L41

Not sure if there are any backwards-incompatible changes in 1.1.1e/1.1.1f/1.1.1g.

**Comment by zhaozg** [comment]
Should be full compatible

**Comment by zhaozg** [comment]
after some work, it's time to do a new release
- [ ] luv
- [ ] lua-openssl
- [ ] openssl
