### ISSUE TITLE
Luvi on arm

### ISSUE THREAD

**Issue by MuffinMonster** [luvit/luvi#235]
First off I'm not sure if this belongs here or in "lit" repo but I'll post it here since the issue stems from luvi usage.

So I managed to download luvi and compile it on an ARM based system and got so far as to try and compile lit using my successfully compiled luvi install. Now low and behold the "core.lua" file prompts for a download of luvi from github releases, even though I've just compiled it locally, and as luvi-regular-Linux_armv71 isn't in the compiled releases, it fails.
This is such a simple redirect to the existing build or even to straight up download the source instead of a prebuilt binary, I really want luvit running on this raspberry pi 3b so a fix for this is greatly appreciated.

Resulting error from running luvi on the lit-src folder
![image](https://user-images.githubusercontent.com/10003312/85228733-d3c8e180-b3ed-11ea-9c6e-349dc0de911c.png)

**Comment by SinisterRectus** [comment]
If you have a custom version of luvi, you can indicate this to lit. You can specify the luvi source to use in the 4th argument of the make line:
```
# Create luvit using lit
./lit make lit://luvit/luvit luvit luvi
```

**Comment by MuffinMonster** [comment]
Well this is in the lit installation phase and I haven't got a lit binary yet. Is it possible to pass a path to luvi when installing lit from source?

**Comment by squeek502** [comment]
From within the lit-src folder:

```
./luvi . -- make . ./lit ./luvi
```

**Comment by MuffinMonster** [comment]
Oh, I see, Thank you a ton!
