### ISSUE TITLE
Error building lit with luvi

### ISSUE THREAD

**Issue by Sukadia** [luvit/luvi#236]
I've used Luvit on my windows computer, but I've been trying to install it for my raspberry pi as of yesterday. I've successfully installed Luvi, but when trying to run the `luvi lit.zip -- lit.zip` command as specified I get the following error:

```lua
fail: [string "bundle:libs/core.lua"]:234: Problem downloading custom luvi: https://github.com/luvit/luvi/releases/download/v2.10.1/luvi-regular-Linux_armv7l
stack traceback:
        [C]: in function 'assert'
        [string "bundle:libs/core.lua"]:234: in function 'getLuvi'
        [string "bundle:libs/core.lua"]:389: in function 'make'
        [string "bundle:commands/make.lua"]:11: in function <[string "bundle:commands/make.lua"]:1>
        [string "bundle:main.lua"]:69: in function <[string "bundle:main.lua"]:56>
        [C]: in function 'xpcall'
        [string "bundle:main.lua"]:56: in function <[string "bundle:main.lua"]:48>
```

I'm not sure what I can do/fix at this point, I'm very new to raspberry pi so I don't know whether this is a fault on my part or the download I installed. Either way, help would be greatly appreciated- thanks in advance!

**Comment by squeek502** [comment]
It will try to download the luvi version specified by lit by default (which doesn't have a prebuilt arm version so that's why it's failing). You need to tell it to use your custom luvi instead:

```
./luvi lit.zip -- make lit.zip ./lit ./luvi
```

**Comment by Sukadia** [comment]
Got it to work- I've successfully run the last two commands in the installation process. The last thing I'm unsure of is where luvit is, since it says I should have that by the end so I can move it to my path. Doesn't seem to be in the luvi folder or usr/local/bin. Do you know where it could be, or did something go wrong?

**Comment by squeek502** [comment]
Once you have lit you can build luvit by doing

```
./lit make lit://luvit/luvit ./luvit ./luvi
```

**Comment by Sukadia** [comment]
Got it! I previously just ran the one on the installation page, but this one works perfectly. Thank you so much!
