### ISSUE TITLE
Build failure with custom LuaJIT (OpenResty fork)

### ISSUE THREAD

**Issue by carlocab** [luvit/luvi#242]
I'm trying to build luvi with a custom LuaJIT, which is the latest release build from the OpenResty fork. This produces the following build error:

```
luajit: unknown luaJIT command or jit.* modules not installed
luajitluajit: unknown luaJIT command or jit.* modules not installed
: unknown luaJIT command or jit.* modules not installed
make[2]: *** [jitted_tmp/src/lua/luvibundle.lua_luvi_generated.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[2]: *** [jitted_tmp/deps/lpeg/re.lua_luvi_generated.o] Error 1
make[2]: *** [jitted_tmp/src/lua/init.lua_luvi_generated.o] Error 1
luajit: unknown luaJIT command or jit.* modules not installed
make[2]: *** [jitted_tmp/src/lua/luvipath.lua_luvi_generated.o] Error 1
make[1]: *** [CMakeFiles/luvi.dir/all] Error 2
make: *** [all] Error 2
```

LuaJIT was built using the standard `make amalg`, so I'm not sure why I'm getting this error. Setting `LUA_PATH` to LuaJIT's `jit` directory as explained in https://github.com/luvit/luvi/commit/a9dc8dae2eb69d4a754a0cf5c08622d70f6b7067 didn't help. Assistance would be appreciated.

Complete build logs: https://gist.github.com/carlocab/2a6c25344be31127f61635d8978b3720

These were generated while attempting a build in Homebrew, but I can reproduce this without Homebrew using just a `make tiny` with the appropriate environment variables for set to enable building with a shared libluv. (I'm actually doing this to assist with Homebrew packaging of luvit. The latest luvi release doesn't build on Apple Silicon.)

**Comment by squeek502** [comment]
Looks like the errors are coming from here:

https://github.com/luvit/luvi/blob/1c7cb3dc71582b490c9a748522f6bdff91ff05d2/cmake/Modules/LuaJITAddExecutable.cmake#L29-L37

where the bundled lua files are compiled using `luajit -b`. Does your custom LuaJIT support the `-b` option?

**Comment by carlocab** [comment]
Seems like it does. I ran the command manually:
```
❯ pwd
/tmp/luvi/src/lua
❯ /bin/ls
init.lua        luvibundle.lua  luvipath.lua
❯ /usr/local/opt/luajit-openresty/bin/luajit -b init.lua init.lua_luvi_generated.o
❯ /bin/ls
init.lua                        init.lua_luvi_generated.o       luvibundle.lua                  luvipath.lua
```

**Comment by squeek502** [comment]
What's LUA_PATH set to when `luajit -b` works? Seems like the error comes from LuaJIT not being able to load things like `bcsave.lua` (similar problem here: https://github.com/openresty/opm/issues/9).

The message in https://github.com/luvit/luvi/commit/a9dc8dae2eb69d4a754a0cf5c08622d70f6b7067 does seem to be relevant.

**Comment by carlocab** [comment]
It's not set to anything. `echo $LUA_PATH` returns nothing. However, when I set it to the `jit` directory:
```
❯ echo $LUA_PATH
/usr/local/opt/luajit-openresty/share/luajit-2.1.0-beta3/jit/?.lua
❯ /usr/local/opt/luajit-openresty/bin/luajit -b init.lua init.lua_luvi_generated.o
/usr/local/opt/luajit-openresty/bin/luajit: unknown luaJIT command or jit.* modules not installed
```
In fact, it seems like setting `LUA_PATH` to an empty variable causes problems:
```
❯ LUA_PATH= /usr/local/opt/luajit-openresty/bin/luajit -b init.lua init.lua_luvi_generated.o
/usr/local/opt/luajit-openresty/bin/luajit: unknown luaJIT command or jit.* modules not installed
```

**Comment by carlocab** [comment]
For reference, these are the contents of the `jit` directory:
```
❯ fd '.*\.lua'
share/luajit-2.1.0-beta3/jit/bc.lua
share/luajit-2.1.0-beta3/jit/bcsave.lua
share/luajit-2.1.0-beta3/jit/dis_arm.lua
share/luajit-2.1.0-beta3/jit/dis_arm64.lua
share/luajit-2.1.0-beta3/jit/dis_arm64be.lua
share/luajit-2.1.0-beta3/jit/dis_mips.lua
share/luajit-2.1.0-beta3/jit/dis_mips64.lua
share/luajit-2.1.0-beta3/jit/dis_mips64el.lua
share/luajit-2.1.0-beta3/jit/dis_mipsel.lua
share/luajit-2.1.0-beta3/jit/dis_ppc.lua
share/luajit-2.1.0-beta3/jit/dis_x64.lua
share/luajit-2.1.0-beta3/jit/dis_x86.lua
share/luajit-2.1.0-beta3/jit/dump.lua
share/luajit-2.1.0-beta3/jit/p.lua
share/luajit-2.1.0-beta3/jit/v.lua
share/luajit-2.1.0-beta3/jit/vmdef.lua
share/luajit-2.1.0-beta3/jit/zone.lua
```

**Comment by squeek502** [comment]
Can you try changing this line:

https://github.com/luvit/luvi/blob/1c7cb3dc71582b490c9a748522f6bdff91ff05d2/cmake/Modules/LuaJITAddExecutable.cmake#L32

to:

```
        COMMAND luajit
```

and see if that fixes it for you?

**Comment by carlocab** [comment]
It works! Tests are running atm. Let's see if that broke anything...

**Comment by squeek502** [comment]
Nice!

I'm not totally sure why that line has the `"LUA_PATH=${LUA_PATH}"`, will need to investigate this more to see if it's necessary at all.

**Comment by carlocab** [comment]
In case it's helpful: I can also reproduce this with a release build of (classic, non-forked) LuaJIT. Of course, that's a bit older than the one pinned in your deps submodule.

**Comment by carlocab** [comment]
I should also actually mention that using a shared libluv also causes errors with how `LPEGLIB_DIR` is set. Without manual intervention, I get this build error:
```
CMake Error in CMakeLists.txt:
  Cannot find source file:

    /tmp/luvit--luvi-20210121-94985-vucl7x/tmp/luvit--luvi-20210121-94985-vucl7x/deps/lpeg/re.lua
```
The correct path to `re.lua` is `tmp/luvit--luvi-20210121-94985-vucl7x/deps/lpeg/re.lua`. Not sure why the prefix is getting doubled there. Setting
```
export LPEGLIB_DIR=deps/lpeg
```
fixes the problem.

**Comment by joerg-krause** [comment]
> Nice!
> 
> I'm not totally sure why that line has the `"LUA_PATH=${LUA_PATH}"` in it currently. Will need to investigate this more to see if it's necessary at all.

`"LUA_PATH=${LUA_PATH}"` was added by me in commit 0be7acc82ddffd8012e458dbb1d09a50e151116d. This allows to use LuaJIT in build environments, where it is not installed in a default location, e.g. when cross-compiling, or when LuaJIT is installed in a custom directory.

**Comment by carlocab** [comment]
I have LuaJIT installed in a non-default location above, but the `LUA_PATH` setting seems to break my build (and getting rid of it fixes it).

**Comment by joerg-krause** [comment]
In case of a non-default location, you should pass `LUA_PATH=/usr/local/opt/luajit-openresty/share/luajit-2.1.0-beta3/jit/?.lua` to the build environment, when compiling luvi.

**Comment by carlocab** [comment]
> In case of a non-default location, you should pass `LUA_PATH=/usr/local/opt/luajit-openresty/share/luajit-2.1.0-beta3/jit/?.lua` to the build environment, when compiling luvi.

But my non-default location works when `luajit` is invoked without setting `LUA_PATH`. It seems to me that we should only be doing `LUA_PATH=${LUA_PATH}` when it's already set in the environment, or else it'll break things even for default locations. See neovim/neovim#16714.
