### ISSUE TITLE
"unprotected error in call to Lua API" with custom ARM binary

### ISSUE THREAD

**Issue by sjkim04** [luvit/luvi#264]
Continuing from https://github.com/luvit/lit/issues/312

> How you build or where do you get luvi?
and ~/Desktop/luvi without any args output any message?

I built it from my Desktop. For a short preview of what commands did I run
```
git clone --recursive -b v2.14.0
cd luvi
make regular
make
make test
```
`make test` **and** `./build/luvi samples/test.app` outputs the same error, which presumably happens in line 8.

`./build/luvi` prints the normal help message.

@zhaozg

**Comment by truemedian** [comment]
unfortunately that error message in the attached issue does not mean line 8, it means error 8, which if I remember correctly is either a table overflow or nan index. you can check lj_errmsg.h for more information

**Comment by zhaozg** [comment]
Please try `make regular WITH_LUA_ENGINE=1`, I guess `luajit -b` cause this issue.

And `uanme -a` will give us detail ARCH/OS info.

**Comment by sjkim04** [comment]
```
$ uname -a
Linux raspberrypi 5.15.32-v7l+ #1538 SMP Thu Mar 31 19:39:41 BST 2022 armv7l GNU/Linux
```
Running `make` now, will report details after build finishes.

**Comment by sjkim04** [comment]
`WITH_LUA_ENGINE=Lua` actually worked! Thank you!
Closing

**Comment by zhaozg** [comment]
`armv7l` is a 32bit CPU,  and not adequate test for 32bit ARM, because lack of test environment.

**Comment by Bilal2453** [comment]
If I am not mistaken, Truemedian was running into this lately with their [automatic GitHub builds](https://github.com/truemedian/luvit-bin/releases).   Seems like it worked for some time then regression in LuaJIT caused this? Probably will need to look into the make script of LuaJIT

**Comment by zhaozg** [comment]
> Probably will need to look into the make script of LuaJIT

Luajit is the more likely cause.

**Comment by zhaozg** [comment]
reproduce with docker, image is `arm32v7/ubuntu:xenial` hash is `20832692ca6e`.

`uname` output `Linux 31112c604e51 5.10.104-linuxkit #1 SMP Thu Mar 17 17:08:06 UTC 2022 armv7l armv7l armv7l GNU/Linux`.

```
build/luvi samples/test.app -- 1 2 3 4
PANIC: unprotected error in call to Lua API (8)
Makefile:91: recipe for target 'test' failed
make: *** [test] Error 1
```
