### ISSUE TITLE
Installing on ARM64 (Ubuntu 20.04)

### ISSUE THREAD

**Issue by WizzDex** [luvit/luvi#266]
Hey, I've got Luvi to install but I can't get to install "lit". I've tried to rebuild it from source and then "sudo install lit /usr/local/bin" but it still didn't work, any ideas?

Error received: bash: /usr/local/bin/lit: cannot execute binary file: Exec format error

**Comment by squeek502** [comment]
Could you provide more info on exactly what steps you're trying?

**Comment by truemedian** [comment]
Closing because no additional information was provided and I cannot discern the actual issue at hand.
