### ISSUE TITLE
Build error (M1 mac)

### ISSUE THREAD

**Issue by taesoobear** [luvit/luvi#267]
There seems to be no native arm binary. So I tried to build from source but it still tries to download some kind of binary (custom luvi?). Why doesn't it use the luvi I just compiled?

...
including dependency: ssh-rsa (deps/ssh-rsa.lua)
including dependency: ustring (deps/ustring.lua)
including dependency: weblit-app (deps/weblit-app.lua)
including dependency: weblit-auto-headers (deps/weblit-auto-headers.lua)
including dependency: weblit-router (deps/weblit-router.lua)
including dependency: weblit-server (deps/weblit-server.lua)
including dependency: weblit-websocket (deps/weblit-websocket.lua)
including dependency: websocket-codec (deps/websocket-codec.lua)
compiling filter: deps/git/** excludes by default (first rule is positive)
including: core.lua
including: db.lua
including: init.lua
including: package.lua
including: storage.lua
creating binary: /Users/taesookwon/lua/luvi/lit
downloading: https://github.com/luvit/luvi/releases/download/v2.12.0/luvi-regular-Darwin_arm64
fail: [string "bundle:libs/core.lua"]:234: Problem downloading custom luvi: https://github.com/luvit/luvi/releases/download/v2.12.0/luvi-regular-Darwin_arm64
stack traceback:                                                                         
        [C]: in function 'assert'                                                        
        [string "bundle:libs/core.lua"]:234: in function 'getLuvi'                       
        [string "bundle:libs/core.lua"]:389: in function 'make'                          
        [string "bundle:commands/make.lua"]:11: in function <[string "bundle:commands/make.lua"]:1>
        [string "bundle:main.lua"]:69: in function <[string "bundle:main.lua"]:56>       
        [C]: in function 'xpcall'                                                        
        [string "bundle:main.lua"]:56: in function <[string "bundle:main.lua"]:48>

**Comment by squeek502** [comment]
To build Lit with custom luvi (instructions are from [here](https://github.com/luvit/lit/#building-from-source)):

```
git clone --recurse-submodules https://github.com/luvit/lit.git
cd lit
./your_luvi . -- make . ./lit ./your_luvi
```

This will create `./lit`

To build Luvit with custom luvi:

```
git clone --recurse-submodules https://github.com/luvit/luvit.git
cd luvit
lit make . ./luvit ./your_luvi
```

**Comment by taesoobear** [comment]
Great! This worked. Thank you.
