### ISSUE TITLE
"rex" should be "rex.pcre"

### ISSUE THREAD

**Issue by zhaozg** [luvit/luvi#269]
https://github.com/luvit/luvi/blob/4115796e4a259e4ba1d6a10454f97955f062ce16/src/main.c#L100

should we rename "rex" to "rex.pcre"?  I think we compat to office version name.

If yes, I can make a PR.

**Comment by squeek502** [comment]
I think the canonical name would be `"rex_pcre"`:
- https://github.com/rrthomas/lrexlib/blob/69d5c442c5a4bdc1271103e88c5c798b605e9ed2/test/runtest.lua#L63
- https://github.com/rrthomas/lrexlib/blob/69d5c442c5a4bdc1271103e88c5c798b605e9ed2/src/pcre/lpcre.c#L23

But this would be a breaking change, so I don't think it's worth it. If you want to also set `preload["rex_pcre"]` to the same value as `preload["rex"]` that might be ok.
