### ISSUE TITLE
Build for Apple's arm64 processors

### ISSUE THREAD

**Issue by onebutter** [luvit/luvi#275]
https://github.com/luvit/luvi/releases/download/v2.14.0/luvi-regular-Darwin_arm64 is missing when I do `curl -L https://github.com/luvit/lit/raw/master/get-lit.sh | sh` to install

Is it possible to cut a build for it?

**Comment by Bilal2453** [comment]
It is possible although we would have to consider using GitHub Actions most probably.
Take a look at this https://github.com/truemedian/luvit-bin/releases.

**Comment by Bilal2453** [comment]
If I remember correctly, there is also an available package on Homebrew that is maintained by a community, works as well.

**Comment by SinisterRectus** [comment]
This is now supported with version [2.15.0](https://github.com/luvit/luvi/releases/tag/v2.15.0).
