### ISSUE TITLE
[string "bundle:main.lua"]:1: module 'weblit' not found:

### ISSUE THREAD

**Issue by benjdoh** [luvit/luvi#277]
I have a simple app using `weblit`

```lua
-- main.lua
local weblit = require('weblit')

local app = weblit.app.bind({ port = 3000 })

app.use(weblit.autoHeaders)

app.route({ path = "/" }, function(req, res)
  res.body = "lol"
end)

app.start()
```

after bundling it with `luvi ./ -o code.exe` and I run it, I get the error.

**Comment by RainyXeon** [comment]
@justboereh You can try to install luvit/luvit package

**Comment by truemedian** [comment]
What has likely happened here is that you are missing luvit's require function that looks into `deps/`. You should be able to lit install `luvit/require` as a dependency, which will allow luvi to pick up and use luvit's require. Please re-open if you continue to encounter this problem with the `luvit/require` package present.
