### ISSUE TITLE
luvi-regular-Linux_aarch64 Support?

### ISSUE THREAD

**Issue by Ashk3000** [luvit/luvi#284]
Im trying to run Luvit on my MacBook with docker. I am able to on my pc but I get an error that https://github.com/luvit/luvi/releases/download/v2.14.0/luvi-regular-Linux_aarch64 doesn't exist. This is the curl command:
`curl -fsSL https://github.com/luvit/lit/raw/master/get-lit.sh | sh`

**Comment by squeek502** [comment]
Luvi doesn't currently provide aarch64 binaries, unfortunately. You'd need to build from source.

Related: https://github.com/luvit/luvi/issues/200

**Comment by SinisterRectus** [comment]
This is now supported with version [2.15.0](https://github.com/luvit/luvi/releases/tag/v2.15.0).
