### ISSUE TITLE
Mingw64 build instructions missing

### ISSUE THREAD

**Issue by fithisux** [luvit/luvi#299]
I cloned and used ucrt64 builds of msys2 packages for the dependencies.

mingw32-make failed.

Are there specific build instructions?

I prefer to use msys2 packages for all the dependencies if possible (openssl, libuv ...)

**Comment by truemedian** [comment]
When using static openssl (the default) Luvi fetches and builds it from source. This requires `mingw32-make` on Windows. `mingw32-make` is provided by the `mingw-w64-x86_64-make` in the `mingw64` repository for MSYS2, so you'll need to install that and make sure that `{MSYS_ROOT}/mingw64/bin` is in your PATH.

If you already have a version of openssl installed you could also subvert the openssl build process by using shared openssl.

**Comment by fithisux** [comment]
How can I do the last step? The first fails

`c:\work\luvit\luvi>mingw32-make regular
process_begin: CreateProcess(NULL, uname -s, ...) failed.
Makefile:121: pipe: No error
cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release -DWITH_AMALG=ON -DWITH_LUA_ENGINE=LuaJIT -DWithSharedLibluv=OFF -DWithOpenSSL=ON -DWithPCRE2=ON -DWithLPEG=ON -DWithZLIB=OFF -DWithOpenSSLASM=ON -DWithSharedOpenSSL=OFF -DWithSharedPCRE2=OFF -DWithSharedLPEG=OFF -DWithSharedZLIB=OFF
-- Found luvi git version: v2.14.0-43-g32b274b
-- summary of build options:
    Install prefix:  C:/Program Files (x86)/luvi
    Target system:   Windows
    Compiler:
      C compiler:    C:/winoss/msys64/ucrt64/bin/cc.exe (GNU)
      CFLAGS:

-- LuaJIT Target: x64
-- LuaJIT target x64
Enabling Static OpenSSL
OPENSSL_CONFIGURE_TARGET: mingw64
OPENSSL_CONFIG_OPTIONS: no-unit-test;no-shared;no-stdio;no-idea;no-mdc2;no-rc5;--prefix=C:/work/luvit/luvi/build
OPENSSL_BUILD_COMMAND: mingw32-make
CMake Warning (dev) at C:/winoss/msys64/ucrt64/share/cmake/Modules/FetchContent.cmake:1373 (message):
  The DOWNLOAD_EXTRACT_TIMESTAMP option was not given and policy CMP0135 is
  not set.  The policy's OLD behavior will be used.  When using a URL
  download, the timestamps of extracted files should preferably be that of
  the time of extraction, otherwise code that depends on the extracted
  contents might not be rebuilt if the URL changes.  The OLD behavior
  preserves the timestamps from the archive instead, but this is usually not
  what you want.  Update your project to the NEW behavior or specify the
  DOWNLOAD_EXTRACT_TIMESTAMP option with a value of true to avoid this
  robustness issue.
Call Stack (most recent call first):
  deps/openssl.cmake:47 (FetchContent_Declare)
  deps/lua-openssl.cmake:1 (include)
  CMakeLists.txt:117 (include)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at deps/openssl.cmake:66 (message):
  Failed to configure OpenSSL
Call Stack (most recent call first):
  deps/lua-openssl.cmake:1 (include)
  CMakeLists.txt:117 (include)


-- Configuring incomplete, errors occurred!
mingw32-make: *** [Makefile:212: regular] Error 1

c:\work\luvit\luvi>`

**Comment by fithisux** [comment]
works like charm

```
mingw32-make regular WITH_SHARED_OPENSSL=ON WITH_SHARED_PCRE2=ON WITH_SHARED_ZLIB=ON
```

Thank you very much. Is this luvi.exe a luajit one?

**Comment by truemedian** [comment]
Yes, you will only get a Lua 5.4 luvi when you provide `WITH_LUA_ENGINE=Lua` or use shared Libluv with a libluv that was compiled with `WITH_LUA_ENGINE=Lua`.

**Comment by fithisux** [comment]
Amazing, I installed lit and litted luvit. Now I have all the binaries.

Fantastic work. Can other projects be litted? Like wxLua?

**Comment by fithisux** [comment]
But for a new one I can use it as I understand like e.g. a Scilab extension I'm planning (Scilab already has a Tcl extension that passes things back and forth to a Tcl interpreter).

**Comment by fithisux** [comment]
I close the ticket since it can now act as a source of information.
