### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dennismak** [luvit/luvi#42]
While building "make" gives error 
Machine is with Debian testing 32 bit

trailing line from make console as under

CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_pow':
buildvm_x86.dasc:(.text+0x28e7): undefined reference to `lj_wrap_pow'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_atan2':
buildvm_x86.dasc:(.text+0x292b): undefined reference to `lj_wrap_atan2'
CMakeFiles/luajit.dir/lj_vm.s.o: In function `lj_ff_math_fmod':
buildvm_x86.dasc:(.text+0x296f): undefined reference to `lj_wrap_fmod'
collect2: error: ld returned 1 exit status
CMakeFiles/luajit.dir/build.make:219: recipe for target 'luajit' failed
make[3]: *** [luajit] Error 1
make[3]: Leaving directory '/home/dennis/Software/Run/luvi/build'
CMakeFiles/Makefile2:130: recipe for target 'CMakeFiles/luajit.dir/all' failed
make[2]: *** [CMakeFiles/luajit.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
[ 65%] Building ASM object CMakeFiles/lua51.dir/lj_vm.s.o
Linking C static library libluajit.a
make[3]: Leaving directory '/ho bitme/dennis/Software/Run/luvi/build'
[ 78%] Built target lua51
make[2]: Leaving directory '/home/dennis/Software/Run/luvi/build'
Makefile:76: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/dennis/Software/Run/luvi/build'
Makefile:21: recipe for target 'luvi' failed
make: *** [luvi] Error 2

**Comment by creationix** [comment]
@dennismak Do you still have this issue?

**Comment by dennismak** [comment]
Thanks, now there are no bulllld errors after update/reset.
