### ISSUE TITLE
Windows Event Log

### ISSUE THREAD

**Issue by rjemanuele** [luvit/luvi#51]
Using the Windows Event Log from Luvi is a tricky proposition without compiling for each change of the logging format.  The old use of the Windows Event system is deprecated in favor of the new Windows Event Log.

Writing to the Windows Event Log requires use of the Message Compiler (mc.exe) to compile the desired message format into a binary format linkable to a DLL.  https://msdn.microsoft.com/en-us/library/windows/desktop/aa363680(v=vs.85).aspx  These tools are freely available as part of the Platform SDK.

A few paths are available to us:
1. Once shared library support is complete we can provide instructions for accessing the Message Format DLL and the API for writing said messages.
2. Include a simple static message format
3. Use the native methods to load the message DLL and use the API for writing said messages.

For the moment, I am leaning toward the last option and providing the API to register a provider message DLL and report events from that DLL.

**Comment by creationix** [comment]
Luvit now supports loading shared libraries out of the luvi bundle. (though I'm not 100% sure I tested that feature on windows).  Also libuv exposes cross-platform dlopen and friends.  Though if this is for the windows-only C code in luvi, there is nothing wrong with using custom windows APIs to load the shared libraries.

**Comment by rjemanuele** [comment]
Obsolete issue
