### ISSUE TITLE
Is luvi support hotfix?

### ISSUE THREAD

**Issue by jackiesun8** [luvit/luvi#73]
I want to use luvit to write a game server framework.So i am more concerned with if luvi support hotfix,especially i buddle the app.

**Comment by imzyxwvu** [comment]
What does hotfixing mean here? luvi is tiny enough so you had better bundle an new executable when you update your framework. Simply publishing your code to lit would work very well if you just want to publish your framework.

If the hotfix here just meant dynamically loading Lua code at runtime. You could try the standard library functions, load and loadfile.

**Comment by jackiesun8** [comment]
@imzyxwvu Ok,thank you very much.
