### ISSUE TITLE
Minor: incorrect argument to loadString in init.lua

### ISSUE THREAD

**Issue by raphaelcohn** [luvit/luvi#81]
https://github.com/luvit/luvi/blob/master/src/lua/init.lua line 427, shouldn't the second argument to `loadstring` be `mainPath` and not `"bundle:main.lua"`?

**Comment by creationix** [comment]
Thanks, fixed in https://github.com/luvit/luvi/commit/4d19f33f0d7c9f9f27b528b68c83fa05cbfb8a6b
