### ISSUE TITLE
Enhancement: Embed libtcc

### ISSUE THREAD

**Issue by raphaelcohn** [luvit/luvi#82]
libtcc is the API part of tcc, the Tiny C Compiler. It is a standalone library for compiling, assembling and linking C code. It is small and very fast.

If we embed libtcc into luvi, then luvit, lit, and other downstream users can:-
- mix C code with lua code in deployed bundles;
- compile at runtime, not build time for a particular platform
- speed up development and deployment
- avoid the need for a cross-compiler tool

For me, this last is the biggest win. Most of the sort of C code needed in luvi applications is of the 'easier to do this bit in C' or 'I need some glue to wrap up this horrible third-party API'; currently, a developer has to run either a set of local cross-compile toolchains (an unmanageable nightmare for most of us) or a build farm (yeah)! Neither are great for rapid prototyping or development where performance isn't the be all and end all.

tcc is _not_ appropriate:-

- where runtime performance is critical; it's slower than optimized output from gcc and clang
- where a target system lacks installed system headers

These could be mitigated, in a number of ways:-
- only allow libtcc when running unbundled applications (aka 'development mode')
- hard-code typical locations (these are well known for Mac OS X, the BSDs and Linux)
- embed the system headers as resources into luvi (nearly all are open source, and this isn't linking)
- allow fallback to looking for .so, etc, as we do now in require.lua; this would also allow those folks that want to use Makefiles or cmake

**Comment by creationix** [comment]
Neat idea.  Could you prototype it as a lit module?  I'm having great luck using ffi with C libraries.  My most recent example is Alex's cross-platform gamepad wrapper https://github.com/creationix/lit-gamepad

When I publish to lit, it includes all the .so and .dll files in the bundle, when when lit installs it as a dependency, it only includes the version that matches the local architecture.

**Comment by raphaelcohn** [comment]
What lit's doing is pretty cool. I'm not sure in that case what I'm proposing is needed as such for luvi. A spanner in the works I've found with libtcc is that it doesn't create dylib on Mac OS X, so it's not as useful.

However, lit isn't probably appropriate for the use cases I'm thinking of using luvi for. My build machine isn't my deployment machine; indeed, I may be deploying to several different target host types. I'm actually exploring scenarios where luvi is used as an IoT firmware which is easily updatable. I'm also want to see my source code. I sometimes need to hack on my dependencies. I'm looking at build-from-source or at least build-from-what's-in-git (preferably using submodules so dependencies can be given proper credit, and one can then uses forks if one needs to hack on dependencies). I prefer a model of development where all my source dependencies are checked in and versioned via git (indeed, with some of the government organisations I've worked with, this is mandatory). It also means one can just checkout-and-go. lit installs. I suppose one could then .gitignore, but that makes it all a bit more unpleasant. In short, I just don't much like language-specific package managers, as they just don't suit my development style (and this goes back a long way to before maven). I've also been badly burnt (npm and bower come to mind; the latter is woefully naive). For me, if one's going down the package manager route, then at least one should copy `deb` / `apt-get` - its solved many of the problems one encounters over many years. With all that said, I know I'm an exception to the majority here.

With lua, this is quite straightforward, as it's mostly just source code one includes. With C code, it's harder. What makes it harder still is I favour rsync-style deployment, and luvi makes that a snap. (rsync deployment makes it more bandwidth efficient for large roll outs, quicker, and easier to sort out problems). The only two remaining pieces of the puzzle are:-

* Making sure luajit dependencies for non-Lua stuff are present (eg, if we're wrapping `libSomething`, say) by deploying them with my rsync-able bundle, rather than relying on whatever package manager there is (and having a far more complex deployment, and brittleness due to version differences, etc)
* Compiling lua-specific code, which is what I was hoping libtcc would do (but probably is a non-starter), on the fly

I've got a bad feeling this is all going to require some sort of cross-compiler toolchain... at which point it's far too complex to be worthwhile.

One approach to the first would be to actually compile luvi with additional C libs statically linked in. This would be quite complex to do, but it would have the advantage that one could then do -fwhole-program / link time optimisation. I suppose ultimately my use case might be just too different to yours, but I'm loathe to go my own way - there's a lot of ***really good stuff*** in luvi. Let me do some more tinkering and see where things go.

**Comment by creationix** [comment]
One solution that's worked well for others (but I personally don't like) is install all the cross-compile toolchains in the cloud and expose them as a service.  Them you simply need to upload your C code and platform description and get back binaries.

My main concern with this is that the level of trust it requires on the cloud services is simply unacceptable, but I appear to be a minority in that opinion.

**Comment by raphaelcohn** [comment]
Tim,

Make that a minority of 2. Whilst I'm all for cloud computing, being able
to build your toolchains and dependencies from source is very important -
particularly in some environments. gcc et al, however, along with autotools
and friends, have made this insanely hard.

Rob Landley's Aboriginal Linux, and EmbToolkit make things a bit easier,
but they're only really solutions for particular cross combinations. Since
this came up, I've been twirling over ideas in my head using luajit to
bootstrap things up. Nothing very concrete or sane, but something around
compiling luajit, which has minimal environment dependencies (and one of
the cleanest make files I've seen in sometime), and then using lua code to
drive a cross compile toolchain generator. Doing it in shell script has
just been insanely hard over the years, as crosstool-ng shows.


Raphael Cohn
Chief Architect, stormmq
Co-Chair, OASIS MQTT Standard
Secretary, OASIS AMQP Standard
raphael.cohn@stormmq.com
+44 7590 675 756

UK Office:
Hamblethorpe Farm, Crag Lane, Bradley BD20 9DB, North Yorkshire, United
Kingdom
Telephone: +44 845 3712 567

Registered office:
16 Anchor Street, Chelmsford, Essex, CM2 0JY, United Kingdom
StormMQ Limited is Registered in England and Wales under Company Number
07175657
StormMQ.com

**Comment by creationix** [comment]
Closing this issue for now since tcc is not a suitable solution.  Please file a new issue if you have any new ideas to help with this.
