### ISSUE TITLE
bundle.register

### ISSUE THREAD

**Issue by develephant** [luvit/luvi#84]
Hi,

I don't see the **bundle.register** method in the docs.  Is that a crucial part?  Because it seems that's the only way to 'require' other Lua mods for apps.  I found it in the samples.

Great work by the way.  Really enjoying Luvi so far.

Cheers.

**Comment by creationix** [comment]
Bundle.register is just a helper for bootstrapping the require system.  It's not a stable API any may go away or change.

**Comment by creationix** [comment]
There is a convention in luvi where it auto-bootstraps luvit/require from lit if it's detected in the deps folder.  (Also pretty-print is auto-loaded if luvit/pretty-print is instlled giving you a global `p` dumper)

Most of my luvi apps contain luvit/require and luvit/pretty-print installed from lit in the deps folder.  This makes bootstrapping much easier and gives me a nice require system that works with the zip bundle and allows relative requires between files (something lua's native require can't do).

**Comment by creationix** [comment]
Closing this as I'd rather deprecate bundle.register than make it an official public API.
