### ISSUE TITLE
Why are headers only installed for shared lib build?

### ISSUE THREAD

**Issue by sousoux** [luvit/luvi#93]
CMakeLists is set to only install headers when a shared library version is built but they are needed for building native modules even in a statically linked luvi.
  
if (BUILD_SHARED_LIBS)
    install(
      FILES src/luv.h src/util.h src/lhandle.h src/lreq.h
      DESTINATION "${INSTALL_INC_DIR}"
    )
  endif (BUILD_SHARED_LIBS)

**Comment by creationix** [comment]
Probably because there is no "install" for statically linked luvi since it's usually just embedded.  But I'm fine with changing the makefile to always include headers.

**Comment by joerg-krause** [comment]
I am fine with installing the header files for the static build too.

@sousoux Do you want to create a PR?
